# Step41, 행렬의 곱 

## 41.1 벡터의 내적과 행렬의 곱 

In [5]:
import numpy as np 

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
print(c)

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a,b)
print(c)

32
[[19 22]
 [43 50]]


~~~python
class MatMul(Function):
    def forward(self, x, W):
        y = x.dot(W)
        return y 
    
    def backward(self, gy):
        x, W = self.inputs 
        gx = matmul(gy, W.T)
        gW = matmul(x.T, gy)
        return gx, gW 

def MatMul(x,W):
    return MatMul()(x,W)
~~~

In [6]:
from dezero import Variable
import dezero.functions as F 

x = Variable(np.random.randn(2,3))
W = Variable(np.random.randn(3,4))
print(x)
print()
print(W)
print()
print()

y = F.matmul(x,W)
print(y)
y.backward()

print(x.grad.shape)
print(W.grad.shape)

variable([[ 1.02437187  0.7196935  -1.31961753]
          [-1.74017625 -0.14155778 -0.64276809]])

variable([[ 0.08274425 -0.64814396  0.00725374 -1.70466895]
          [-0.52677748  0.23058883  0.59225761 -1.25847331]
          [-0.67679155 -0.39812694  1.03595286 -0.98078785]])


variable([[ 0.59874855  0.02738812 -0.93338707 -1.35766514]
          [ 0.36559988  1.35114637 -0.7623389   3.77499024]])
(2, 3)
(3, 4)
